PZ/Projektni centar zadatak/Models/Preduzeca.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

PZ/Projektni centar zadatak/Controllers/KontaktiController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Projektni_centar_zadatak.Models;

namespace Projektni_centar_zadatak.Controllers
{
    public class KontaktiController : Controller
    {
        #region ParcijalniPregledi
        // GET: Kontakti
        public PartialViewResult MailLista(KontaktOsoba kontakt)
        {

            return PartialView(kontakt.MailKontakts.ToList());
        }

        public PartialViewResult TelefonLista(KontaktOsoba kontakt)
        {
            TempData["ID"] = kontakt.ID.ToString();
            return PartialView(kontakt.TelefonKontakts.ToList());
        }
        #endregion
        #region DodavanjeUBazu
        [HttpPost]
        public ActionResult DodavanjeTelefona(TelefonKontakt tel)
        {

            
            ProjektniZadatakEntities1 entities = new ProjektniZadatakEntities1();
            KontaktOsoba kontos = entities.KontaktOsobas.FirstOrDefault(x => x.ID == tel.IDKontakt);
            if (kontos != null)
            {
                TelefonKontakt duplikat = entities.TelefonKontakts.FirstOrDefault(x => x.BrojTelefona == tel.BrojTelefona);
                if (duplikat == null)
                {
                    entities.TelefonKontakts.Add(tel);
                    entities.SaveChanges();
                    return RedirectToAction("MenadzmentKontakt", "Preduzeca", new { id = kontos.IDpreduzeca });
                }
                else
                {
                   
                    duplikat.Greska = true;
                    TempData["msg"] = "Isti broj telefona vec postoji!";
                    return View("DodajBroj", duplikat);
                   
                }
            }
            else
            {
                return RedirectToAction("Greska", "Home");
            }
        }

        [HttpPost]
        public ActionResult DodavanjeMaila(MailKontakt mail)
        {

            ProjektniZadatakEntities1 entities = new ProjektniZadatakEntities1();
            
            KontaktOsoba kontos = entities.KontaktOsobas.FirstOrDefault(x => x.ID == mail.IDKontakt);
            
            if (kontos != null)
            {
                MailKontakt duplikat = entities.MailKontakts.FirstOrDefault(x => x.Adresa == mail.Adresa);
                if (duplikat == null)
                {
                    entities.MailKontakts.Add(mail);
                    entities.SaveChanges();
                    return RedirectToAction("MenadzmentKontakt", "Preduzeca", new { id = kontos.IDpreduzeca });
                }
                else
                {
                    duplikat.Greska = true;
                    TempData["msg"] = "Ista mail adresa vec postoji!";
                    return View("DodajMail", duplikat);
                }
            }
            else
            {
                return RedirectToAction("Greska", "Home");
            }
            
           
        }
        [HttpPost]
        public ActionResult DodavanjeKontaktOsobe(KontaktOsoba kontos)
        {
            ProjektniZadatakEntities1 entities1 = new ProjektniZadatakEntities1();
            Preduzece preduzece = entities1.Preduzeces.FirstOrDefault(x => x.ID == kontos.IDpreduzeca);
            if (preduzece != null)
            {
                entities1.KontaktOsobas.Add(kontos);
                entities1.SaveChanges();
                return RedirectToAction("MenadzmentKontakt", "Preduzeca", new { id = kontos.IDpreduzeca });
            }
            else
            {
                return RedirectToAction("Greska", "Home");
            }
        }
       
        #endregion
        #region DodavanjePregledi
         public ActionResult DodajKontaktOsobu(int ID)
        {
            KontaktOsoba kontakt = new KontaktOsoba();
            kontakt.IDpreduzeca = ID;
            return View(kontakt);
        }
        public ActionResult DodajMail(KontaktOsoba kont)
        {
            MailKontakt Mail = new MailKontakt();
            Mail.IDKontakt = kont.ID;
            Mail.KontaktOsoba = kont;
            return View(Mail);
        }
       
        public ActionResult DodajBroj(KontaktOsoba kont)
        {
            TelefonKontakt telefon = new TelefonKontakt();
            telefon.IDKontakt = kont.ID;
            telefon.KontaktOsoba = kont;
            return View(telefon);
        }
        #endregion
        #region Brisanje
        [HttpPost]

        public ActionResult ObrisiMail(MailKontakt mail)
        {
            
            ProjektniZadatakEntities1 entities1 = new ProjektniZadatakEntities1();
            KontaktOsoba kontos = entities1.KontaktOsobas.FirstOrDefault(x => x.ID == mail.IDKontakt);
            MailKontakt t = entities1.MailKontakts.FirstOrDefault(x => x.Adresa == mail.Adresa);
            if (t != null)
            {
                entities1.MailKontakts.Remove(t);
                entities1.SaveChanges();
                
            }
            if (kontos != null)
            {
                return RedirectToAction("MenadzmentKontakt", "Preduzeca", new { id = kontos.IDpreduzeca });
            }
            else
                return RedirectToAction("Greska", "Home");
        }
        [HttpPost]
        public ActionResult ObrisiTelefon(TelefonKontakt telefon)
        {

            ProjektniZadatakEntities1 entities1 = new ProjektniZadatakEntities1();
            KontaktOsoba kontos = entities1.KontaktOsobas.FirstOrDefault(x => x.ID == telefon.IDKontakt);
            TelefonKontakt t = entities1.TelefonKontakts.FirstOrDefault(x => x.BrojTelefona == telefon.BrojTelefona);
            if (t != null)
            {
               
                entities1.TelefonKontakts.Remove(t);
                entities1.SaveChanges();
                
            }
            if (kontos != null)
            {
                return RedirectToAction("MenadzmentKontakt", "Preduzeca", new { id = kontos.IDpreduzeca });
            }
            else
            {
                return RedirectToAction("Greska", "Home");
            }

        }
        [HttpPost]
        public ActionResult ObrisiKontaktOsobu(KontaktOsoba kontakt)
        {

            ProjektniZadatakEntities1 entities1 = new ProjektniZadatakEntities1();
            KontaktOsoba kontos = entities1.KontaktOsobas.FirstOrDefault(x => x.ID == kontakt.ID);
            if (kontos != null)
            {
                
                entities1.MailKontakts.RemoveRange(kontos.MailKontakts.ToList());
                entities1.TelefonKontakts.RemoveRange(kontos.TelefonKontakts.ToList());
                entities1.KontaktOsobas.Remove(kontos);
                entities1.SaveChanges();
               
            }
            return RedirectToAction("MenadzmentKontakt", "Preduzeca", new { id = kontakt.IDpreduzeca });

        }
        #endregion
    }
}

PZ/Projektni centar zadatak/Controllers/PreduzecaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Projektni_centar_zadatak.Models;
using System.IO;

namespace Projektni_centar_zadatak.Controllers
{
    public class PreduzecaController : Controller
    {
        // GET: Preduzeca
        public ActionResult PrikaziSve()
        {
            var preduzeca = new ProjektniZadatakEntities1();
            return View(preduzeca.Preduzeces.ToList());
        }

        public ActionResult Detalji(int ID)
        {
            ProjektniZadatakEntities1 pred = new ProjektniZadatakEntities1();
            Preduzece Preduzece = pred.Preduzeces.FirstOrDefault(x => x.ID == ID);
            if(Preduzece != null)
            {

                return View(Preduzece);
            }
            return RedirectToAction("PrikaziSve", "Preduzeca");

           
        }
        [HttpPost]
       public ActionResult Obrisi(int ID)
        {

            ProjektniZadatakEntities1 entities = new ProjektniZadatakEntities1();
            Preduzece preduzece = entities.Preduzeces.FirstOrDefault(x => x.ID == ID);
            if (preduzece != null)
            {
                if(preduzece.FotografijaPecata != null)
                {
                    string fullPath = Request.MapPath(preduzece.FotografijaPecata);
                    if (System.IO.File.Exists(fullPath))
                    {
                        System.IO.File.Delete(fullPath);
                    }
                }
                var kontakti = preduzece.KontaktOsobas.ToList();
                foreach (KontaktOsoba k in kontakti)
                {
                    entities.MailKontakts.RemoveRange(k.MailKontakts.ToList());
                    entities.TelefonKontakts.RemoveRange(k.TelefonKontakts.ToList());
                }
                entities.KontaktOsobas.RemoveRange(kontakti);
                entities.Preduzeces.Remove(preduzece);
                entities.SaveChanges();

                return RedirectToAction("PrikaziSve", "Preduzeca");
            }
            return RedirectToAction("PrikaziSve", "Preduzeca");
        }
        #region parcijalniKontakt
        public PartialViewResult PartKontakti(int ID)
        {
            ProjektniZadatakEntities1 pre = new ProjektniZadatakEntities1();
            var kontakti = pre.KontaktOsobas.Where(x => x.IDpreduzeca == ID);

            return PartialView(kontakti.ToList());
        }
        public PartialViewResult PartTelefoni(int ID)
        {
            ProjektniZadatakEntities1 pre = new ProjektniZadatakEntities1();
            var telefoni = pre.TelefonKontakts.Where(x => x.IDKontakt == ID);
            return PartialView(telefoni.ToList());
        }
        public PartialViewResult PartMail(int ID)
        {
            ProjektniZadatakEntities1 pre = new ProjektniZadatakEntities1();
            var mailovi = pre.MailKontakts.Where(x => x.IDKontakt == ID);
            return PartialView(mailovi.ToList());
        }
        #endregion
        
        public ActionResult Dodaj()
        {
            return View();
        }
        [HttpPost]
        public ActionResult DodajPreduzece(Preduzece dodajP)
        {
            
            ProjektniZadatakEntities1 pred = new ProjektniZadatakEntities1();
            if (dodajP.ImageFile != null)
            {
                string fileName = Path.GetFileNameWithoutExtension(dodajP.ImageFile.FileName);

                string ext = Path.GetExtension(dodajP.ImageFile.FileName);

                fileName = fileName + DateTime.Now.ToString("yymmssfff") + ext;
                dodajP.FotografijaPecata = "~/Images/" + fileName;

                fileName = Path.Combine(Server.MapPath("~/Images/") + fileName);
                dodajP.ImageFile.SaveAs(fileName);
            }
            pred.Preduzeces.Add(dodajP);
            pred.SaveChanges();
            
           
            
            return RedirectToAction("PrikaziSve", "Preduzeca");
        }
        public ActionResult MenadzmentKontakt(int ID)
        {
            ProjektniZadatakEntities1 preduzece = new ProjektniZadatakEntities1();
            Preduzece pr = preduzece.Preduzeces.FirstOrDefault(x => x.ID == ID);
            if (pr != null)
            {
                TempData["NazivPreduzeca"] = preduzece.Preduzeces.Where(x => x.ID == ID).FirstOrDefault().NazivPreduzeca;
                TempData["ID"] = ID;

                return View(pr.KontaktOsobas.ToList());
            }
            return RedirectToAction("PrikaziSve", "Preduzeca");
        }
        [HttpPost]
       public ActionResult IzmeniPreduzece(Preduzece preduzece)
        {
            return View(preduzece);

           
        }
        public ActionResult SnimiIzmene(Preduzece pred)
        {
            ProjektniZadatakEntities1 entities1 = new ProjektniZadatakEntities1();
            Preduzece preduzece = entities1.Preduzeces.FirstOrDefault(x => x.ID == pred.ID);
            if(preduzece != null)
            {
                preduzece.NazivPreduzeca = pred.NazivPreduzeca;
                preduzece.MatBR = pred.MatBR;
                preduzece.Adresa = pred.Adresa;
                preduzece.BrojRacuna = pred.BrojRacuna;
                preduzece.PIB = pred.PIB;
                preduzece.Opstina = pred.Opstina;
                preduzece.PostanskiBR = pred.PostanskiBR;
                preduzece.WebStranica = pred.WebStranica;
                preduzece.Beleska = pred.Beleska;
                entities1.SaveChanges();
                return RedirectToAction("PrikaziSve", "Preduzeca");
            }
            return RedirectToAction("Greska", "Home");
        }
    }
}

PZ/Projektni centar zadatak/Views/Preduzeca/Detalji.cshtml
@model Projektni_centar_zadatak.Models.Preduzece

@{

   
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Detalji</title>
    <script type="text/javascript">
        function print_page() {
            var ButtonControl = document.getElementById("btnprint");
            ButtonControl.style.visibility = "hidden";
            var btnControl = document.getElementById("btnVrati");
            btnControl.style.visibility = "hidden";
            window.print();


            btnControl.style.visibility = "visible";
            ButtonControl.style.visibility = "visible";
        }

    </script>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div style="position:relative;left:5%">
        <h2>Preduzece: @Model.NazivPreduzeca</h2>
        <hr />
        <dl class="dl-horizontal">




            <dt>
                @Html.DisplayNameFor(model => model.Adresa)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Adresa)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Opstina)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Opstina)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.PostanskiBR)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.PostanskiBR)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.MatBR)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.MatBR)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.PIB)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.PIB)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.BrojRacuna)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.BrojRacuna)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.WebStranica)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.WebStranica)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.FotografijaPecata)
            </dt>

            <dd>
                @if (Model.FotografijaPecata != null)
                {
                <img src="@Url.Content(Model.FotografijaPecata)" height="250" width="250"/>
                }
                else
                {
                    <p>Slika ne postoji.</p>
                }
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Beleska)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Beleska)
            </dd>

        </dl>
        <hr />
        <hr />
        <p>Kontakt osobe:</p>
        @{ Html.RenderAction("PartKontakti", (int)Model.ID);}
        @using (Html.BeginForm("PrikaziSve", "Preduzeca"))
        {
        <input type="submit" id="btnVrati" value="Povratak na pregled preduzeca" class="btn btn-default" style="background-color: #f4f2f2" />
        }

        <div>
            <input type="button" id="btnprint" value="Odstampaj formu" onclick="print_page()" class="btn btn-default" style="background-color: #f4f2f2" />
        </div>
    </div>
    

    
        
    
</body>
</html>

PZ/Projektni centar zadatak/Views/Preduzeca/Dodaj.cshtml
@model Projektni_centar_zadatak.Models.Preduzece
@if ((int?)Session["PravoPristupa"] == 1)
{
    Response.Redirect("~/login/index");
}
@{


    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Dodaj</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/jqueryval")


    @using (Html.BeginForm("DodajPreduzece", "Preduzeca", FormMethod.Post, new { enctype = "multipart/form-data" }))
    {
        

        <div class="form-horizontal">
            <h2>Dodavanje novog preduzeca</h2>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group">
                @Html.LabelFor(model => model.NazivPreduzeca, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.NazivPreduzeca, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.NazivPreduzeca, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Adresa, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Adresa, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Adresa, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Opstina, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Opstina, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Opstina, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.PostanskiBR, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.PostanskiBR, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.PostanskiBR, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.MatBR, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.MatBR, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.MatBR, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.PIB, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.PIB, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.PIB, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.BrojRacuna, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.BrojRacuna, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.BrojRacuna, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.WebStranica, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.WebStranica, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.WebStranica, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.FotografijaPecata, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    <input type="file" name="ImageFile"  accept=".png , .jpg , .jpeg" />
                </div>
            </div>

                

         

            <div class="form-group">
                @Html.LabelFor(model => model.Beleska, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Beleska, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Beleska, "", new { @class = "text-danger" })
                </div>
            </div>


            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">


                    <input type="submit" value="Dodaj novo preduzece" class="btn btn-default" style="background-color: #f4f2f2" />

                </div>
            </div>
        </div>
    }

    @using (Html.BeginForm("PrikaziSve", "Preduzeca"))
    {
        <input type="submit" value="Otkazi dodavanje" class="btn btn-default" style="background-color: #f4f2f2" />
    }
</body>
</html>

PZ/Projektni centar zadatak/Views/Preduzeca/MenadzmentKontakt.cshtml
@model IEnumerable<Projektni_centar_zadatak.Models.KontaktOsoba>
@if ((int?)Session["PravoPristupa"] == 1)
{
    Response.Redirect("~/Home/Index");
}
@{


    int IDpred = (int)TempData["ID"];
    Layout = null;
}
@Styles.Render("~/Content/css")
@Scripts.Render("~/bundles/modernizr")
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>MenadzmentKontakt</title>
</head>

<body>
    <h1>Menadzment kontakt osoba preduzeca: @TempData["NazivPreduzeca"]</h1>
    @using (Html.BeginForm("PrikaziSve", "Preduzeca"))
    {
        <input type="submit" value="Povratak na listu preduzeca" class="btn btn-default" style="background-color: #f4f2f2" />
    }
    <hr />

    @using (Html.BeginForm("DodajKontaktOsobu", "Kontakti", new { id = IDpred }))
    {
        <input type="submit" value="Dodaj novu kontakt osobu" class="btn btn-default" style="background-color: #f4f2f2" />
    }
    <hr />
    <table class="table">
        <tr style="background-color: #f4f2f2">
            <th>
                @Html.DisplayNameFor(model => model.Ime)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Prezime)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.RadnoMesto)
            </th>

            <th>Mail adrese</th>
            <th>Telefonski brojevi</th>
            <th></th>
            <th></th>
        </tr>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Ime)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Prezime)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.RadnoMesto)
                </td>

                <td>
                    @using (Html.BeginForm("DodajMail", "Kontakti", item, FormMethod.Post))
                    {
                        <input type="submit" value="Dodaj novu mail adresu" class="btn btn-default" style="background-color: #f4f2f2" />
                    }
                    @{ Html.RenderAction("MailLista", "Kontakti", item);}

                </td>

                <td>
                    @using (Html.BeginForm("DodajBroj", "Kontakti", item, FormMethod.Post))
                    {
                        <input type="submit" value="Dodaj novi Broj telefona" class="btn btn-default" style="background-color: #f4f2f2" />
                    }
                    @{ Html.RenderAction("TelefonLista", "Kontakti", item);}
                </td>
                <td>
                    @using (Html.BeginForm("ObrisiKontaktOsobu", "Kontakti", item, FormMethod.Post))
                    {
                        <input type="submit" value="Obrisi kontakt osobu" onclick="return confirm('Molimo potvrdite brisanje kontakta: @item.Ime')" class="btn btn-default" style="background-color: #f4f2f2" />
                    }
                </td>
            </tr>
        }

    </table>
</body>
</html>

PZ/Projektni centar zadatak/Views/Preduzeca/PartKontakti.cshtml
@model IEnumerable<Projektni_centar_zadatak.Models.KontaktOsoba>



@if (Model.Count() != 0)
{
    foreach (var item in Model)
    {


<dl class="dl-horizontal">
    <dt>
        Ime:
    </dt>
    <dd>
        @Html.DisplayFor(modelItem => item.Ime)
    </dd>
    <dt>
        Prezime:
    </dt>

    <dd>
        @Html.DisplayFor(modelItem => item.Prezime)
    </dd>
    <dt>
        Radno mesto:
    </dt>

    <dd>
        @Html.DisplayFor(modelItem => item.RadnoMesto)
    </dd>

     
</dl>
        Html.RenderAction("PartTelefoni",new {ID = item.ID });
        Html.RenderAction("PartMail", new { ID = item.ID });
        <hr />

    }
}
else
{
    <p><b>Nema kontakt osoba</b></p>
}

PZ/Projektni centar zadatak/Views/Preduzeca/PartMail.cshtml
@model IEnumerable<Projektni_centar_zadatak.Models.MailKontakt>

<div>
    <p>Mail adrese:</p>
    @if(Model.Count() != 0)
        {
        foreach (var item in Model)
        {
        <p><b>@Html.DisplayFor(model => item.OznakaTip):</b> @Html.DisplayFor(model => item.Adresa)</p>

        }
    }
    else
    {
        <p><b>Nema mail adresu</b></p>
    }
</div>

PZ/Projektni centar zadatak/Views/Preduzeca/PartTelefoni.cshtml
@model IEnumerable<Projektni_centar_zadatak.Models.TelefonKontakt>

<div>
    <p>Telefoni:</p>
    @{if (Model.Count() != 0)
        {
            foreach (var item in Model)
            {
                <p><b>@Html.DisplayFor(model => item.OznakaTip):</b> @Html.DisplayFor(model => item.BrojTelefona) Lokal: @Html.DisplayFor(model => item.Lokal)</p>

            }
        }

        else
        {
                <p><b>Nema telefon</b></p>
        }
    }
</div>